# 应用名称
spring:
  application:
    name: purview-manage
  freemarker:
    # 模板地址
    template-loader-path: classpath:/templates/ftl/
    # 关闭缓存，及时刷新，上线生产环境需要修改为true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    settings:
      template_update_delay: 0
      classic_compatible: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/perview?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  # 静态资源加载配置
  mvc:
    static-path-pattern: /static/**

# 端口号
server:
  port: 8089

mybatis-plus:
  type-aliases-package: com.crossrainbow.pm.server.service.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    id-type: 0 # 0:数据库自增id 1:用户输入id 2: 全局唯一id 3: 全局唯一uuid
    field-strategy: 2 # 0: 忽略判断 1: 非null判断 2: 非空判断
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false




